# Generated by Django 2.1.5 on 2019-01-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qcm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateEdited', models.DateField(auto_now=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice_1', models.CharField(max_length=150)),
                ('choice_2', models.CharField(max_length=150)),
                ('choice_3', models.CharField(max_length=150)),
                ('choice_4', models.CharField(max_length=150)),
                ('id_qcm', models.ForeignKey(on_delete='CASCADE', to='Qcm.Qcm')),
            ],
        ),
    ]
