# Generated by Django 2.1.5 on 2019-01-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qcm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('choiceA', models.CharField(max_length=150)),
                ('choiceB', models.CharField(max_length=150)),
                ('choiceC', models.CharField(max_length=150)),
                ('choiceD', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=4)),
                ('qcmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qcm.Qcm')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('qcmId', 'num')},
        ),
    ]
