# Generated by Django 2.1.5 on 2019-01-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_4',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
