# Generated by Django 2.1.5 on 2019-01-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcm',
            name='dateCreated',
            field=models.DateField(auto_now=True),
        ),
    ]
