# Generated by Django 2.1.5 on 2019-01-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qcm', '0002_auto_20190126_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcm',
            name='dateCreated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
