# Generated by Django 2.1.5 on 2019-01-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qcm', '0002_auto_20190123_2045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
