# Generated by Django 2.1.5 on 2019-01-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qcm', '0003_auto_20190123_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choiceC',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choiceD',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
