# Generated by Django 2.1.5 on 2019-01-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('sujet', models.CharField(max_length=20)),
                ('redaction', models.TextField()),
                ('nb_replies', models.IntegerField(default=0)),
                ('date_poste', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
