# Generated by Django 2.1.5 on 2019-01-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='rep_publication',
            field=models.IntegerField(default=1),
        ),
    ]
