# Generated by Django 2.1.5 on 2019-01-25 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_auto_20190125_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='user',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='reponse',
            old_name='user',
            new_name='auteur',
        ),
    ]
