# Generated by Django 2.1.5 on 2019-01-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_auto_20190125_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='auteur',
        ),
    ]
