# Generated by Django 2.1.5 on 2019-01-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_auto_20190125_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='nb_replies',
        ),
    ]
