# Generated by Django 2.1.4 on 2019-01-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connexion', '0003_auto_20190124_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiare',
            name='faculte',
            field=models.CharField(default='mohamed 5', max_length=100),
            preserve_default=False,
        ),
    ]
