# Generated by Django 2.1.4 on 2019-01-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=150)),
                ('professeur', models.CharField(max_length=200)),
                ('support_pdf', models.CharField(max_length=100)),
                ('video_src', models.CharField(max_length=100)),
            ],
        ),
    ]
