# Generated by Django 2.1.4 on 2019-01-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='video_src',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
