# Generated by Django 2.1.4 on 2019-01-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_auto_20190124_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='titre',
            new_name='title',
        ),
    ]
