# Generated by Django 2.1.4 on 2019-01-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0005_auto_20190124_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='video_src',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
