# Generated by Django 2.1.4 on 2019-01-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0006_auto_20190124_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasClinique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=200)),
                ('support_pdf', models.CharField(max_length=100)),
                ('corrige_src', models.CharField(max_length=100)),
                ('video_src', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
