# Generated by Django 2.1.4 on 2019-01-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0008_auto_20190124_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='support_pdf',
            field=models.FileField(upload_to='cours/pdfs/'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='video_src',
            field=models.FileField(null=True, upload_to='cours/videos/'),
        ),
    ]
