# Generated by Django 2.1.4 on 2019-01-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0009_auto_20190125_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cascliniques',
            name='corrige_src',
            field=models.FileField(upload_to='cas-clinique/corriges/'),
        ),
        migrations.AlterField(
            model_name='cascliniques',
            name='support_pdf',
            field=models.FileField(upload_to='cas-clinique/pdfs/'),
        ),
        migrations.AlterField(
            model_name='cascliniques',
            name='video_src',
            field=models.FileField(null=True, upload_to='cas-clinique/videos/'),
        ),
    ]
