# Generated by Django 2.1.4 on 2019-01-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0010_auto_20190125_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cascliniques',
            name='video_src',
            field=models.FileField(blank=True, null=True, upload_to='cas-clinique/videos/'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='video_src',
            field=models.FileField(blank=True, null=True, upload_to='cours/videos/'),
        ),
    ]
